---

gcal_colors:
  Unset: &Unset
    id: "0"
    background: null
  Lavender: &Lavender
    id: "1"
    background: "#a4bdfc"
  Sage: &Sage
    id: "2"
    background: "#33b679"
  Grape: &Grape
    id: "3"
    background: "#8e24aa"
  Flamingo: &Flamingo
    id: "4"
    background: "#e67c73"
  Banana: &Banana
    id: "5"
    background: "#f6c026"
  Tangerine: &Tangerine
    id: "6"
    background: "#f5511d"
  Peacock: &Peacock
    id: "7"
    background: "#039be5"
  Graphite: &Graphite
    id: "8"
    background: "#616161"
  Blueberry: &Blueberry
    id: "9"
    background: "#3f51b5"
  Basil: &Basil
    id: "10"
    background: "#0b8043"
  Tomato: &Tomato
    id: "11"
    background: "#d60000"

event_categories:
  "misc":
    cover_color: "#000000"
    gcal_color: *Unset
  "los-verdes":
    bg_color: "#000000"
    text_bg_color: "#00b140"
    text_fg_color: "#FFFFFF"
    default_cover_image: "https://drive.google.com/file/d/1dv2K9ep6wldSqYbhH8nizRQW2PTPwdLW/view?usp=sharing"
    always_shown_in_filters: true
    gcal_color: *Lavender
  "la-murga":
    cover_color: "#000000"
    always_shown_in_filters: true
    gcal_color: *Sage
  "home-games":
    cover_color: "#dbadff"
    always_shown_in_filters: true
    gcal_color: *Grape
  "away-games":
    cover_color: "#000000"
    always_shown_in_filters: true
    gcal_color: *Flamingo

mls_teams:
  atl:
    name: Atlanta United
    color: "#9d2235"
  cin:
    name: FC Cincinnati
    color: "#003087"
  clt:
    name: Charlotte FC
    color: "#0085ca"
  col:
    name: Colorado Rapids
    color: "#8a2432"
  dal:
    name: FC Dallas
    color: "#c6093b"
  dc:
    name: D.C. United
    color: "#212121"
  hou:
    name: Houston Dynamo FC
    color: "#101820"
  la:
    name: LA Galaxy
    color: "#004b87"
  lafc:
    name: LAFC
    color: "#212121"
  mia:
    name: Inter Miami CF
    color: "#212322"
  min:
    name: Minnesota United
    color: "#737b82"
  mtl:
    name: "CF Montr\xE9al"
    color: "#212121"
  nsh:
    name: Nashville SC
    color: "#201547"
  orl:
    name: Orlando City
    color: "#61259e"
  por:
    name: Portland Timbers
    color: "#004812"
  rbny:
    name: New York Red Bulls
    color: "#ba0c2f"
  rsl:
    name: Real Salt Lake
    color: "#001e61"
  sea:
    name: Seattle Sounders FC
    color: "#64a608"
  sj:
    name: San Jose Earthquakes
    color: "#0051ba"
  skc:
    name: Sporting Kansas City
    color: "#0c2340"
  van:
    name: Vancouver Whitecaps FC
    color: "#002244"
