name: Build and Publish Site

on:
  workflow_call:
    # inputs:
    #   site_hostname:
    #     default: 'los-verdes-events.asfasfsafsasfa.org'
    #     required: false
    #     type: string
    #   cdn_zone_name:
    #     default: 'asfasfsafsasfa.org'
    #     required: false
    #     type: string
    #   calendar_id:
    #     default: 'information@losverdesatx.org'
    #     required: false
    #     type: string

jobs:
  terraform-outputs:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_terraform_outputs.yml@main

  build-and-publish-site:
    name: Build and Publish Site
    needs: terraform-outputs
    runs-on: ubuntu-latest
    environment: prod-site
    env:
      EVENTS_PAGE_CALENDAR_ID: "${{ inputs.calendar_id }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/538480189659/locations/global/workloadIdentityPools/los-verdes-events/providers/los-verdes-events-provider'
          service_account: 'gh-publisher-los-verdes-events@losverdesatx-events.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.2.1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        working-directory: events_page
        run: pip3 install --requirement=requirements.txt

      - name: Build and Publish Site
        working-directory: events_page
        env:
          EVENTS_PAGE_BASE_DOMAIN: "${{ needs.terraform-outputs.outputs.cdn_zone_name }}"
          EVENTS_PAGE_CALENDAR_ID: "${{ needs.terraform-outputs.outputs.calendar_id }}"
          EVENTS_PAGE_GCS_BUCKET_NAME: "${{ needs.terraform-outputs.outputs.bucket_id }}"
          EVENTS_PAGE_GITHUB_REPO: "${{ github.repository }}"
          EVENTS_PAGE_HOSTNAME: "${{ needs.terraform-outputs.outputs.bucket_id }}"
          EVENTS_PAGE_WEBHOOK_TOKEN_SECRET_NAME: "${{ needs.terraform-outputs.outputs.webhook_token_secret_name }}"
          EVENTS_PAGE_WEBHOOK_URL: "${{ needs.terraform-outputs.outputs.webhook_url }}"
        run: |
          ./build_and_publish_site.py \
            --site-hostname="${{ needs.terraform-outputs.outputs.bucket_id }}" \
            --cdn-zone-name="${{ needs.terraform-outputs.outputs.cdn_zone_name }}"
