name: Build and Publish Site

concurrency:
  group: "build-and-publish-${{ github.ref }}"
  cancel-in-progress: false

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build-and-publish-site:
    name: Build and Publish Site
    runs-on: ubuntu-latest
    environment: prod-site
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/538480189659/locations/global/workloadIdentityPools/jeffwecan-lv-event-pagenerator/providers/jeffwecan-lv-event-pagenerator"
          service_account: "gh-terraform-applier@losverdesatx-events.iam.gserviceaccount.com"

      - name: Retrieve cached dotenv file
        uses: actions/cache@v2
        with:
          path: events_page/.env
          key: events-page-dotenv-${{ github.sha }}

      - name: Build and Publish Site
        run: just build-and-publish
