name: Cleanup Test Site Prefix

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-test-site-prefix:
    name: Cleanup Test Site Prefix
    runs-on: ubuntu-latest
    environment:
      name: ${{ format('tests/pr-{0}', github.event.number) }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Utilize pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ env.pythonLocation }}-${{ hashFiles('events_page/requirements.txt') }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/538480189659/locations/global/workloadIdentityPools/jeffwecan-lv-event-pagenerator/providers/jeffwecan-lv-event-pagenerator"
          service_account: "test-site-publisher@losverdesatx-events.iam.gserviceaccount.com"

      - name: Cleanup Test Site Prefix
        run: |
          just \
            --set export_tf_vars true
            cleanup-test-site-prefix
        env:
          EVENTS_PAGE_GCS_BUCKET_PREFIX: ${{ format('tests/pr-{0}', github.event.number) }}
