name: Ensure GCal and GDrive Watches

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  load-events-env:
    permissions:
      contents: "read"
      id-token: "write"
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_events_env.yml@main

  ensure-watches:
    name: Ensure GCal and GDrive Watches
    needs: load-events-env
    runs-on: ubuntu-latest
    environment: prod-site
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Read .terraform-version
        id: read_tf_version
        run: |
          echo "::set-output name=terraform_version::$(cat ./.terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.read_tf_version.outputs.terraform_version }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/538480189659/locations/global/workloadIdentityPools/jeffwecan-lv-event-pagenerator/providers/jeffwecan-lv-event-pagenerator"
          service_account: "site-publisher@losverdesatx-events.iam.gserviceaccount.com"

      - name: Ensure GCal and GDrive Watches
        run: just ensure-watches
