name: Ensure Watches

on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch: {}

jobs:
  terraform-outputs:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_terraform_outputs.yml@main

  ensure-watches:
    name: Ensure GCal and GDrive Watches
    needs: terraform-outputs
    runs-on: ubuntu-latest
    environment: prod-site
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/538480189659/locations/global/workloadIdentityPools/los-verdes-events/providers/los-verdes-events-provider'
          service_account: 'gh-publisher-los-verdes-events@losverdesatx-events.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0.2.1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        working-directory: events_page
        run: pip3 install --requirement=requirements.txt

      - name: Ensure GCal and GDrive Watches
        working-directory: events_page
        env:
          EVENTS_PAGE_BASE_DOMAIN: "${{ needs.terraform-outputs.outputs.cdn_zone_name }}"
          EVENTS_PAGE_CALENDAR_ID: "${{ needs.terraform-outputs.outputs.calendar_id }}"
          EVENTS_PAGE_GCS_BUCKET_NAME: "${{ needs.terraform-outputs.outputs.bucket_id }}"
          EVENTS_PAGE_GITHUB_REPO: "${{ github.repository }}"
          EVENTS_PAGE_HOSTNAME: "${{ needs.terraform-outputs.outputs.bucket_id }}"
          EVENTS_PAGE_WEBHOOK_TOKEN_SECRET_NAME: "${{ needs.terraform-outputs.outputs.webhook_token_secret_name }}"
          EVENTS_PAGE_WEBHOOK_URL: "${{ needs.terraform-outputs.outputs.webhook_url }}"
        run: |
          # TODO: figure out canonical location for settings-file-name and such when finalizing setting arrangements
          ./ensure_watches.py \
            --calendar-id="${{ needs.terraform-outputs.outputs.calendar_id }}" \
            --settings-file-name='event_page_settings.yaml' \
            --gdrive-folder-name='lv-event-cover-images'
