name: Ensure Watches

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch: {}

jobs:
  load-events-env:
    permissions:
      contents: "read"
      id-token: "write"
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_events_env.yml@main

  ensure-watches:
    name: Ensure GCal and GDrive Watches
    needs: load-events-env
    runs-on: ubuntu-latest
    environment: prod-site
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/538480189659/locations/global/workloadIdentityPools/jeffwecan-lv-event-pagenerator/providers/jeffwecan-lv-event-pagenerator"
          service_account: "site-publisher@losverdesatx-events.iam.gserviceaccount.com"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0.2.1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        working-directory: events_page
        run: pip3 install --requirement=requirements.txt

      - name: Ensure GCal and GDrive Watches
        working-directory: events_page
        env: ${{ fromJSON(needs.load-events-env.outputs.events_page_env) }}
        run: |
          # TODO: figure out canonical location for settings-file-name and such when finalizing setting arrangements
          ./ensure_watches.py \
            --calendar-id="${{ env.EVENTS_PAGE_CALENDAR_ID }}" \
            --settings-file-name='event_page_settings.yaml' \
            --gdrive-folder-name='lv-event-cover-images'
