name: pull-request-tests

on:
  pull_request:
    branches: [main]
    types: [reopened, opened, synchronize, edited]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # TODO: Do a TF plan here?
  super-linter:
    name: "Lint Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Super Linter
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VALIDATE_TERRAFORM_TERRASCAN: false  # TODO: toggle on after patching up these violations...
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_TERRAFORM: true

  publish-test-site-prefix:
    name: Publish Test Site Prefix
    runs-on: ubuntu-latest
    environment:
      name: ${{ format('tests/pr-{0}', github.event.number) }}
      url: ${{ steps.build-and-publish-test-site.outputs.site_url }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Utilize pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ env.pythonLocation }}-${{ hashFiles('events_page/requirements.txt') }}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/538480189659/locations/global/workloadIdentityPools/jeffwecan-lv-event-pagenerator/providers/jeffwecan-lv-event-pagenerator"
          service_account: "test-site-publisher@losverdesatx-events.iam.gserviceaccount.com"

      - name: Build and Publish Test Site
        id: build-and-publish-test-site
        run: |
          just \
            --set export_tf_vars true \
            build-and-publish
        env:
          # EVENTS_PAGE_CALENDAR_ID: "2urei2qv0edsscn71iamri0ok4@group.calendar.google.com"
          EVENTS_PAGE_GCS_BUCKET_PREFIX: ${{ format('tests/pr-{0}', github.event.number) }}

      - name: Echo site_url output
        run: |
          echo "site_url output: ${{ steps.build-and-publish-test-site.outputs.site_url }}"
