name: Deploy Infrastructure & Run Build


concurrency:
  group: "deploy-main-branch"
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  # TODO:? run the PR workflow here first? To cover a plan and jazz....

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: prod-gcp-project
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/538480189659/locations/global/workloadIdentityPools/los-verdes-events/providers/los-verdes-events-provider'
          service_account: 'gh-owner-los-verdes-events@losverdesatx-events.iam.gserviceaccount.com'

      - name: Read .terraform-version
        id: read_tf_version
        run: |
          echo "::set-output name=terraform_version::$(cat ./.terraform-version)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.read_tf_version.outputs.terraform_version }}

      - name: Init - terraform
        run: terraform init
        working-directory: terraform

      - name: Plan - terraform
        run: terraform plan -var-file=../losverdesatx-events.tfvars
        working-directory: terraform
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.cloudflare_api_token }}
          TF_VAR_site_publisher_github_pat: ${{ secrets.site_publisher_github_pat }}

      - name: Apply - terraform
        run: terraform apply -var-file=../losverdesatx-events.tfvars -auto-approve
        working-directory: terraform

  load-events-env:
    needs: deploy-infrastructure
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_events_env.yml@main

  build-site:
    needs: load-events-env
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/build_and_publish_site.yml@main
    with:
      events_page_env: ${{ needs.load-events-env.outputs.events_page_env }}
