name: Trigger Site Build

on:
  workflow_dispatch: {}

jobs:
  load-events-env:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_events_env.yml@main

  build-site:
    needs: load-events-env
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/build_and_publish_site.yml@main
    with:
      events_page_env: ${{ needs.load-events-env.outputs.events_page_env }}
