name: Trigger Site Build

on:
  workflow_dispatch:
    inputs:
      site_hostname:
        default: 'los-verdes-events.asfasfsafsasfa.org'
        description: 'Fully-qualified domain name of the published site. Used in cache purging / priming methods.'
        required: true
      cdn_zone_name:
        default: 'asfasfsafsasfa.org'
        description: 'Name of zone at CDN provider (Cloudflare only provider currently considered / supported).'
        required: true

jobs:
  terraform-outputs:
    needs: deploy-infrastructure
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/load_terraform_outputs.yml@main

  build-site:
    needs: terraform-outputs
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: jeffwecan/lv-event-pagenerator/.github/workflows/build_and_publish_site.yml@main
    with:
      events_page_env: ${{ needs.job1.terraform-outputs.events_page_env }}
      site_hostname: ${{ needs.job1.terraform-outputs.bucket_id }}
      calendar_id: ${{ needs.job1.terraform-outputs.cdn_zone_name }}
